#!/usr/bin/env bash

# -----------------------------------------------------
# Helper functions
# -----------------------------------------------------

function check_stack_context {
  if [[ -z "${PIHOLE_WEB_ADMIN_PASS:-}" ]]; then
    log_warning "PIHOLE_WEB_ADMIN_PASS isn't set, web UI will be accessible without authentication."
  fi
}

function build_secrets {
  if [[ ! -f "$SECRETS/ca.crt" || ! -f "$SECRETS/ca.key" ]]; then
    make-ca pihole -o "$SECRETS"
    make-truststore pihole "$SECRETS/ca.crt" -o "$SECRETS"
  fi
  
  if [[ ! -f "$SECRETS/pihole.crt" || ! -f "$SECRETS/pihole.key" ]]; then
    make-cert pihole "$PIHOLE_NODES" -o "$SECRETS" --ca-crt "$SECRETS/ca.crt" --ca-key "$SECRETS/ca.key"
  fi

  cat "$SECRETS/pihole.crt" "$SECRETS/pihole.key" > "$SECRETS/pihole.pem"
}

function install_base_blocklists {
  local node container_id

  for node in $PIHOLE_PRIMARY_FQDN_NODES $PIHOLE_SECONDARY_FQDN_NODES; do
    container_id=$(docker -H "ssh://$node" ps --filter "name=${STACK}_primary_pihole" --filter status=running -q)
  
    docker -H "ssh://$node" exec "$container_id" pihole-FTL gravity.db \
      "INSERT INTO adlist (address, enabled, comment) VALUES ('https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/pro.txt', 1, 'hagezi Pro')"
    
    docker -H "ssh://$node" exec "$container_id" pihole-FTL gravity.db \
      "INSERT INTO adlist (address, enabled, comment) VALUES ('https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/tif.txt', 1, 'hagezi TIF')"

    docker -H "ssh://$node" exec "$container_id" pihole -g
  done
}

# -----------------------------------------------------
# Override functions
# -----------------------------------------------------

function run_clean {
  local primary_confirm secondary_confirm

  log_info "'clean' has been overriden by stack."

  if docker stack ps "${STACK}_primary"; then
    read -r -p "Teardown primary? [yes/N]: " primary_confirm
    if [[ "$primary_confirm" == "yes" ]]; then
      docker stack rm "${STACK}_primary" --detach=false
    fi
  fi

  if docker stack ps "${STACK}_secondary"; then
    read -r -p "Teardown secondary? [yes/N]: " secondary_confirm
    if [[ "$secondary_confirm" == "yes" ]]; then
      docker stack rm "${STACK}_secondary" --detach=false
    fi
  fi
}

function run_status {
  log_info "'status' has been overriden by stack."

  log_info "Getting primary status."
  docker stack ps "${STACK}_primary"

  log_info "Getting secondary status."
  docker stack ps "${STACK}_secondary"
}

# -----------------------------------------------------
# Stack functions
# -----------------------------------------------------

function stack_check_env {
  if [ ! -d "$SECRETS" ]; then
    echo "Configs or secrets directory are missing from '$ENVIRONMENT_BASE'."
    exit 1
  fi
}

function stack_discover {
  export PIHOLE_NODES="$PIHOLE_PRIMARY_NODES $PIHOLE_PRIMARY_FQDN_NODES $PIHOLE_SECONDARY_NODES $PIHOLE_SECONDARY_FQDN_NODES"

  export PIHOLE_PRIMARY_REPLICAS=$(count "$PIHOLE_PRIMARY_NODES")
  export UNBOUND_PRIMARY_REPLICAS=$(count "$UNBOUND_PRIMARY_NODES")

  export PIHOLE_SECONDARY_REPLICAS=$(count "$PIHOLE_SECONDARY_NODES")
  export UNBOUND_SECONDARY_REPLICAS=$(count "$UNBOUND_SECONDARY_NODES")

  export PIHOLE_PRIMARY_DNS_UPSTREAMS=$(
    for host in $UNBOUND_PRIMARY_FQDN_NODES; do
      ip=$(getent hosts "$host" | awk '{print $1}')
      printf "%s#%s;" "$ip" "$UNBOUND_DNS_PORT"
    done
  )

  export PIHOLE_SECONDARY_DNS_UPSTREAMS=$(
    for host in $UNBOUND_SECONDARY_FQDN_NODES; do
      ip=$(getent hosts "$host" | awk '{print $1}')
      printf "%s#%s;" "$ip" "$UNBOUND_DNS_PORT"
    done
  )
}

function stack_env {
  echo
  echo "PIHOLE IMAGE            = $PIHOLE_IMAGE"
  echo "PIHOLE PRIMARY NODES    = ($PIHOLE_PRIMARY_REPLICAS)"
  list "$PIHOLE_PRIMARY_NODES"
  echo
  echo "PIHOLE SECONDARY NODES  = ($PIHOLE_SECONDARY_REPLICAS)"
  list "$PIHOLE_SECONDARY_NODES"
  echo
  echo "PRIMARY DNS UPSTREAM    = $PIHOLE_PRIMARY_DNS_UPSTREAMS"
  echo "SECONDARY DNS UPSTREAM  = $PIHOLE_SECONDARY_DNS_UPSTREAMS"
  echo
  echo "UNBOUND IMAGE           = $UNBOUND_IMAGE"
  echo "UNBOUND PRIMARY NODES   = ($UNBOUND_PRIMARY_REPLICAS)"
  list "$UNBOUND_PRIMARY_NODES"
  echo
  echo "UNBOUND SECONDARY NODES = ($UNBOUND_SECONDARY_REPLICAS)"
  list "$UNBOUND_SECONDARY_NODES"
  echo
}

function stack_deploy {
  build_secrets
  log_info "Checking if primary and/or secondary need to be deployed..."

  if ! docker stack ps "${STACK}_primary" >/dev/null 2>&1; then
    log_info "Deploying primary."
    docker stack deploy --detach=true \
      -c pihole.yml \
      -c unbound.yml \
      -c primary.yml \
      "${STACK}_primary"
  fi

  if ! docker stack ps "${STACK}_secondary" >/dev/null 2>&1; then
    log_info "Deploying secondary."
    docker stack deploy --detach=true \
      -c pihole.yml \
      -c unbound.yml \
      -c secondary.yml \
      "${STACK}_secondary"
  fi

  log_info "Installing default blocklists"
  install_base_blocklists
}
