services:
  unbound:
    hostname: unbound{{.Task.Slot}}
    image: $UNBOUND_IMAGE
    configs:
      - source: unbound_conf
        target: /usr/local/unbound/unbound.conf
      - source: pihole_conf
        target: /usr/local/unbound/conf.d/pihole.conf
      - source: trust_anchor_conf
        target: /usr/local/unbound/conf.d/trust-anchor.conf
    environment:
      TZ: Europe/London

configs:
  unbound_conf:
    file: $CONFIGS/unbound.conf
  pihole_conf:
    file: $CONFIGS/pihole.conf
  trust_anchor_conf:
    file: $CONFIGS/trust-anchor.conf
