server:
    module-config: "validator iterator"

    username: ""
    chroot: ""
    directory: "/usr/local/unbound"

    tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"

include-toplevel: "/usr/local/unbound/conf.d/*.conf"
